### ISSUE TITLE
Descriptive stats

### ISSUE THREAD

**Issue by bbaudry** [castor-software/pankti-experiments#1]
Add the following in the table of https://github.com/castor-software/pankti-experiments/blob/master/README.md
- number of methods
- number of test methods (approximated by number of `@Test`)

**Comment by gluckzhang** [comment]
Also add the following two:

- number of considered pure & non-covered methods by the test suite with JaCoCo
- number of considered pure & pseudo methods by the test suite with Descartes

**Comment by gluckzhang** [comment]
The mentioned metrics have been added in the table. A corresponding table is also created on Overleaf. I'm closing this issue :coffee:
